### ISSUE TITLE
literature_search.py - 'None' use in variable initialization

### ISSUE THREAD

**Issue by alcantarar** [alcantarar/literature_update#23]
``keywords = [None]*papers_length`` in ``literature_search.py`` results in an error. 

Switch to this to fix:  
``... = ['']*papers_length`` for title/abstract/keyword/etc. initialization

**Comment by GBruening** [comment]
I was having another bug when using a blank string, so I switched to none. 

It should be addressed in the most recent commit ce0dd08f927abcb6bd3edf52d3199111b59fe2e5, but this bug may show up later again for another variable.
